---
- name: Actualizar índice de paquetes apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar paquetes base
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Configurar zona horaria
  community.general.timezone:
    name: "{{ timezone }}"

- name: Asegurar sincronización de hora activa
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Instalar unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Habilitar actualizaciones automáticas de seguridad
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    mode: '0644'
